export const MOOD_HISTORY = [
  { day: 'L', short: 'Lun', value: 3, emoji: '😔', label: 'Difficile' },
  { day: 'M', short: 'Mar', value: 5, emoji: '😐', label: 'Neutre' },
  { day: 'M', short: 'Mer', value: 7, emoji: '🌸', label: 'Bien' },
  { day: 'J', short: 'Jeu', value: 4, emoji: '😴', label: 'Fatiguée' },
  { day: 'V', short: 'Ven', value: 6, emoji: '🌸', label: 'Bien' },
  { day: 'S', short: 'Sam', value: 8, emoji: '✨', label: 'Sereine' },
  { day: 'A', short: "Auj", value: 7, emoji: '✨', label: 'Sereine' },
];

export const PAIN_HISTORY = [6, 4, 5, 7, 3, 4, 3];

export const CYCLE_PHASES = [
  { name: 'Menstruelle', days: '1–5', color: '#B892FF', desc: 'Douceur et repos' },
  { name: 'Folliculaire', days: '6–13', color: '#6C3DBA', desc: 'Énergie croissante' },
  { name: 'Ovulatoire', days: '14–16', color: '#E4B008', desc: 'Pic de vitalité' },
  { name: 'Lutéale', days: '17–28', color: '#8B7BA8', desc: 'Recentrage intérieur' },
];

export const PRACTITIONERS = [
  {
    id: 1,
    name: 'Dr. Claire Dubois',
    spec: 'Gynécologue experte',
    tags: ['Endométriose', 'Pelvi-périnéologie'],
    dist: '2.4 km',
    rating: 4.9,
    reviews: 120,
    nextSlot: 'Demain · 10h00',
    price: '60€',
    available: true,
    initials: 'CD',
    bg: 'linear-gradient(135deg, #E9D8FF 0%, #C4A8FF 100%)',
    bio: "Spécialisée dans la prise en charge des douleurs pelviennes chroniques et le diagnostic de l'endométriose. Approche bienveillante et pluridisciplinaire.",
    slots: ['09:00', '10:30', '14:00', '15:30', '17:00'],
  },
  {
    id: 2,
    name: 'Nadia Lefort',
    spec: 'Ostéopathe pelvienne',
    tags: ['Douleurs pelviennes', 'Post-opératoire'],
    dist: '3.1 km',
    rating: 4.8,
    reviews: 86,
    nextSlot: 'Vendredi · 09h30',
    price: '70€',
    available: true,
    initials: 'NL',
    bg: 'linear-gradient(135deg, #FFF8E4 0%, #F5D060 100%)',
    bio: 'Ostéopathe diplômée spécialisée dans les troubles fonctionnels du périnée et la douleur pelvienne chronique liée à l\'endométriose.',
    slots: ['09:30', '11:00', '14:30', '16:00'],
  },
  {
    id: 3,
    name: 'Marie Leroy',
    spec: 'Naturopathe holistique',
    tags: ['Hormones', 'Nutrition anti-inflammatoire'],
    dist: '5.0 km',
    rating: 5.0,
    reviews: 47,
    nextSlot: 'Lundi · 11h00',
    price: '55€',
    available: true,
    initials: 'ML',
    bg: 'linear-gradient(135deg, #E4F0FF 0%, #A8CDFF 100%)',
    bio: 'Accompagnement naturopathique global : alimentation anti-inflammatoire, phytothérapie et gestion du stress pour les femmes atteintes d\'endométriose.',
    slots: ['10:00', '11:30', '13:30', '15:00', '16:30'],
  },
  {
    id: 4,
    name: 'Dr. Sofiane Aït',
    spec: 'Médecin intégratif',
    tags: ['Médecine fonctionnelle', 'Douleur chronique'],
    dist: '6.2 km',
    rating: 4.7,
    reviews: 63,
    nextSlot: 'Mercredi · 14h00',
    price: '80€',
    available: false,
    initials: 'SA',
    bg: 'linear-gradient(135deg, #E4FFED 0%, #A8FFCA 100%)',
    bio: 'Médecin formé à la médecine fonctionnelle. Approche globale combinant biologie, nutrition et thérapies douces pour réduire l\'inflammation systémique.',
    slots: ['14:00', '15:30', '17:00'],
  },
  {
    id: 5,
    name: 'Isabelle Morin',
    spec: 'Psychologue · TCC',
    tags: ['Douleur chronique', 'Gestion émotionnelle'],
    dist: '1.8 km',
    rating: 4.9,
    reviews: 94,
    nextSlot: 'Jeudi · 18h00',
    price: '90€',
    available: true,
    initials: 'IM',
    bg: 'linear-gradient(135deg, #FFE4F5 0%, #FFA8DE 100%)',
    bio: 'Psychologue clinicienne spécialisée dans l\'accompagnement des femmes souffrant de douleurs chroniques. Thérapies cognitivo-comportementales et EMDR.',
    slots: ['09:00', '11:00', '14:00', '18:00'],
  },
];

export const NOTIFICATIONS = [
  { id: 1, type: 'appointment', icon: '📅', title: 'Rappel rendez-vous', body: 'Dr. Claire Dubois · Demain à 10h00', time: '5 min', read: false, color: '#E9D8FF' },
  { id: 2, type: 'community', icon: '💜', title: 'Nouvelle réponse', body: 'Leila a répondu à ton témoignage', time: '23 min', read: false, color: '#FFE4F5' },
  { id: 3, type: 'report', icon: '📊', title: 'Rapport mensuel prêt', body: 'Ton bilan de juillet est disponible', time: '1h', read: false, color: '#FFF8E4' },
  { id: 4, type: 'achievement', icon: '🏆', title: 'Succès débloqué !', body: '7 jours consécutifs · Série en feu 🔥', time: '3h', read: true, color: '#E4F0FF' },
  { id: 5, type: 'health', icon: '💊', title: 'Rappel traitement', body: 'Prise de Visanne · Ce soir à 20h00', time: 'Hier', read: true, color: '#E4FFED' },
  { id: 6, type: 'meditation', icon: '🧘', title: 'Nouvelle méditation', body: '"Soulagement pelvien" · 8 min', time: 'Hier', read: true, color: '#EDE4FF' },
  { id: 7, type: 'community', icon: '🌸', title: 'Post populaire', body: 'Ton témoignage a touché 156 personnes', time: '2 jours', read: true, color: '#FFE4F5' },
];

export const ACHIEVEMENTS = [
  { id: 1, icon: '🔥', title: '7 jours de suite', desc: 'Connectée 7 jours consécutifs', xp: 50, unlocked: true, date: '4 juil.' },
  { id: 2, icon: '📖', title: 'Première entrée', desc: 'Tu as noté tes premiers symptômes', xp: 20, unlocked: true, date: '1 juin' },
  { id: 3, icon: '🧘', title: 'Initiation zen', desc: 'Première session de méditation', xp: 30, unlocked: true, date: '3 juin' },
  { id: 4, icon: '🩺', title: 'Prise en charge', desc: 'Premier rendez-vous réservé', xp: 40, unlocked: true, date: '15 juin' },
  { id: 5, icon: '💜', title: 'Soutien mutuel', desc: 'Premier commentaire de soutien', xp: 25, unlocked: true, date: '20 juin' },
  { id: 6, icon: '🌙', title: 'Nuit apaisée', desc: '5 méditations au coucher', xp: 35, unlocked: true, date: '28 juin' },
  { id: 7, icon: '✨', title: '30 jours de suite', desc: 'Un mois entier de suivi', xp: 100, unlocked: false, progress: 23, total: 30 },
  { id: 8, icon: '📅', title: 'Mois complet', desc: '30 entrées journal en 1 mois', xp: 80, unlocked: false, progress: 18, total: 30 },
  { id: 9, icon: '🏆', title: 'Guerrière de lumière', desc: '100 jours consécutifs', xp: 200, unlocked: false, premium: true, progress: 23, total: 100 },
  { id: 10, icon: '👑', title: 'Experte de son cycle', desc: '12 cycles complets enregistrés', xp: 150, unlocked: false, premium: true, progress: 4, total: 12 },
  { id: 11, icon: '🌺', title: 'Ambassadrice', desc: '50 messages de soutien', xp: 120, unlocked: false, premium: true, progress: 12, total: 50 },
  { id: 12, icon: '💎', title: 'EndoSoul Elite', desc: 'Tous les succès débloqués', xp: 500, unlocked: false, premium: true, progress: 6, total: 12 },
];

export const COMMUNITY_POSTS = [
  {
    id: 1,
    initials: 'M',
    bg: 'linear-gradient(135deg, #EDE4FF 0%, #D4B8FF 100%)',
    color: '#6C3DBA',
    user: 'Anonyme',
    time: 'Il y a 2h',
    tag: '#Victoire',
    tagColor: '#6C3DBA',
    tagBg: '#EDE4FF',
    text: "Aujourd'hui, j'ai enfin trouvé une gynécologue qui m'écoute vraiment. Après 4 ans d'errance médicale… Ne perdez pas espoir les filles ! 💜",
    likes: 24,
    hearts: 38,
    replies: 5,
    saved: false,
  },
  {
    id: 2,
    initials: 'L',
    bg: 'linear-gradient(135deg, #FFE4E4 0%, #FFC4C4 100%)',
    color: '#E46B6B',
    user: 'Anonyme',
    time: 'Il y a 5h',
    tag: '#Soutien',
    tagColor: '#E46B6B',
    tagBg: '#FFE4E4',
    text: "Grosse crise de douleur ce matin… vos astuces naturelles pour faire passer ça quand la bouillotte ne suffit plus ? 🙏",
    likes: 12,
    hearts: 19,
    replies: 8,
    saved: false,
  },
  {
    id: 3,
    initials: 'A',
    bg: 'linear-gradient(135deg, #E4EDFF 0%, #C4D8FF 100%)',
    color: '#6B96E4',
    user: 'Anonyme',
    time: 'Hier',
    tag: '#Témoignage',
    tagColor: '#6B96E4',
    tagBg: '#E4EDFF',
    text: "Premier jour post-opératoire (coelioscopie). C'est dur mais je me sens soulagée de savoir qu'on m'a enfin diagnostiquée officiellement. Stade 3.",
    likes: 156,
    hearts: 204,
    replies: 32,
    saved: true,
  },
  {
    id: 4,
    initials: 'S',
    bg: 'linear-gradient(135deg, #E4FFE4 0%, #B8F0B8 100%)',
    color: '#2E8B57',
    user: 'Anonyme',
    time: 'Il y a 2 jours',
    tag: '#Conseils',
    tagColor: '#2E8B57',
    tagBg: '#E4FFE4',
    text: "Le curcuma associé au poivre noir a vraiment aidé à réduire mon inflammation. Combiné au régime anti-inflammatoire, j'ai moins de crises ce mois-ci 🌿",
    likes: 67,
    hearts: 89,
    replies: 14,
    saved: false,
  },
];

export const STORIES = [
  { initials: 'Toi', bg: 'linear-gradient(135deg, #B892FF, #6C3DBA)', color: 'white', isOwn: true },
  { initials: 'M', bg: 'linear-gradient(135deg, #EDE4FF, #D4B8FF)', color: '#6C3DBA', isOwn: false },
  { initials: 'L', bg: 'linear-gradient(135deg, #FFE4E4, #FFC4C4)', color: '#E46B6B', isOwn: false },
  { initials: 'A', bg: 'linear-gradient(135deg, #E4EDFF, #C4D8FF)', color: '#6B96E4', isOwn: false },
  { initials: 'S', bg: 'linear-gradient(135deg, #FFF8E4, #F5D060)', color: '#C49B00', isOwn: false },
  { initials: 'R', bg: 'linear-gradient(135deg, #FFE4F5, #FFA8DE)', color: '#C44E92', isOwn: false },
];

export const MONTHLY_STATS = {
  daysTracked: 23,
  avgPain: 4.2,
  avgMood: 6.1,
  meditationSessions: 8,
  totalMeditationMinutes: 96,
  symptomsLogged: 23,
  communityMessages: 5,
  appointmentsKept: 2,
  streakMax: 12,
  monthName: 'Juillet 2025',
};

export const BOOKING_DATES = [
  { label: 'Lun', date: '7', full: '7 juil.' },
  { label: 'Mar', date: '8', full: '8 juil.' },
  { label: 'Mer', date: '9', full: '9 juil.' },
  { label: 'Jeu', date: '10', full: '10 juil.' },
  { label: 'Ven', date: '11', full: '11 juil.' },
  { label: 'Sam', date: '12', full: '12 juil.' },
];
